#!/usr/bin/env bash
# bootstrap.sh — clone-clean installer for the memory engine's OUT-OF-REPO wiring.
#
# Sibling of bootstrap.mjs: that script reproduces the DATA TREE (memory/ dirs); this one reproduces the
# wiring that lives OUTSIDE any repo and so can't be version-controlled directly. On a fresh clone you run
# both to recreate the working setup.
#
# THIS iteration installs the "dreaming" pass (STATE: Memory — NEXT): a nightly timer that runs
#   node memory-engine/reconcile.mjs --reflect
#   node memory-engine/mechanical-insights.mjs scan   (DESIGN §6a.8 — dream.sh's second step)
# off-peak, unattended (DESIGN §5/§8; MEM-16 two-tempo; MEM-25 runtime). The lockfile already
# fences it against a manual run; judge() is already brain-neutral.
# On Linux: a systemd user timer. On macOS: a launchd user agent.
#
# It ALSO reproduces the OM-2 home shell wiring (clone-clean): the ~/.hermes/SOUL.md → shells/SOUL.md
# symlink (how `hermes -z` loads the operator shell as identity slot #1) + the ~/CLAUDE.md @-import loader
# and the ~/SOUL.md signpost; AND the Claude Code memory hooks in ~/.claude/settings.json (capture write
# hooks + the OPEN-9 recall read hook + autoMemoryEnabled:false). (Still tracked separately, NOT yet folded
# in: the ~/.hermes config capture hook, the skills bridge — add them here once reconciled.)
#
# Idempotent + clone-clean: timer configs resolve paths from $HOME; every path resolves relative to this
# script, no secrets. Safe to re-run.
#
# EVERYTHING this script does writes OUTSIDE the repo tree (home files, systemd/launchd),
# so every section is gated behind an explicit flag and the default run is REPORT-ONLY
# (mirrors bootstrap.mjs). On a laptop still live on another tree, a flagless run is safe.
#
# Usage:
#   bootstrap.sh                    report-only: print what each flag would write, touch nothing
#   bootstrap.sh --write-hermes     link ~/.hermes/SOUL.md → shells/SOUL.generated.md
#   bootstrap.sh --write-loaders    write ~/CLAUDE.md loader + ~/SOUL.md signpost
#   bootstrap.sh --write-settings   merge memory hooks into ~/.claude/settings.json
#   bootstrap.sh --write-timer      install + enable the nightly timer units
#   bootstrap.sh --cutover          all of the above
#   bootstrap.sh --install-only     with --write-timer/--cutover: install unit files ONLY (no linger, no enable)

set -euo pipefail

INSTALL_ONLY=0; WRITE_HERMES=0; WRITE_LOADERS=0; WRITE_SETTINGS=0; WRITE_TIMER=0
for arg in "$@"; do
  case "$arg" in
    --install-only)   INSTALL_ONLY=1 ;;
    --write-hermes)   WRITE_HERMES=1 ;;
    --write-loaders)  WRITE_LOADERS=1 ;;
    --write-settings) WRITE_SETTINGS=1 ;;
    --write-timer)    WRITE_TIMER=1 ;;
    --cutover)        WRITE_HERMES=1; WRITE_LOADERS=1; WRITE_SETTINGS=1; WRITE_TIMER=1 ;;
    *) echo "bootstrap: unknown flag $arg" >&2; exit 2 ;;
  esac
done

ENGINE_DIR="$(cd "$(dirname "$0")" && pwd -P)"   # <repo>/memory-engine

# ── OM-2 home shell wiring (clone-clean; installed regardless of systemd) ─────────────────────────
# The operator shell loads via a symlink ~/.hermes/SOUL.md → shells/SOUL.md (`hermes -z` injects it as
# identity slot #1; SOUL.md can't @-import — that is builder-only). The two home files are thin loaders/
# signposts over the canonical in-repo shells. Idempotent: symlink replaced in place; files written only
# when their content drifts (no mtime churn).
COCKPIT_ROOT="$(dirname "$ENGINE_DIR")"
SHELLS_DIR="$COCKPIT_ROOT/shells"
# MEM-32 seam, bash mirror of paths.mjs's MEMORY_ROOT resolution.
MEMORY_ROOT="${COCKPIT_MEMORY_ROOT:-$COCKPIT_ROOT/memory}"

install_file() {  # $1=path  $2=content — write only if missing or changed
  if [ ! -e "$1" ] || [ "$(cat "$1" 2>/dev/null)" != "$2" ]; then
    printf '%s\n' "$2" > "$1"
    echo "bootstrap: wrote $1"
  else
    echo "bootstrap: $1 already current"
  fi
}

# Hermes loads the CONCAT (SOUL.md + doctrine.md), generated by bootstrap.mjs (layout §4);
# run `node "$COCKPIT_ROOT/bootstrap.mjs"` first if the generated file is missing.
if [ "$WRITE_HERMES" -eq 1 ]; then
  mkdir -p "$HOME/.hermes"
  ln -sfn "$SHELLS_DIR/SOUL.generated.md" "$HOME/.hermes/SOUL.md"   # operator load wiring (OM-2; layout §4)
  echo "bootstrap: linked ~/.hermes/SOUL.md → $SHELLS_DIR/SOUL.generated.md"
else
  echo "bootstrap: SKIPPED (--write-hermes): would link ~/.hermes/SOUL.md → $SHELLS_DIR/SOUL.generated.md"
fi

if [ "$WRITE_LOADERS" -eq 1 ]; then
install_file "$HOME/CLAUDE.md" "<!-- Loader. The canonical builder shell is version-controlled at $SHELLS_DIR/CLAUDE.md and imported below — edit it there, not here. -->

@$SHELLS_DIR/CLAUDE.md"

install_file "$HOME/SOUL.md" "<!-- Pointer only — nothing loads this file. Hermes loads the operator shell via the symlink
     ~/.hermes/SOUL.md → $SHELLS_DIR/SOUL.generated.md (\`hermes -z\` injects it as identity slot #1).
     SOUL.md cannot use the Claude Code @-import (builder-only); the symlink is the wiring.
     Edit the canonical shells at $SHELLS_DIR/{SOUL.md,doctrine.md}, not here. -->

# Global Hermes Operator Shell — pointer

Canonical: $SHELLS_DIR/SOUL.md + doctrine.md  (loaded by Hermes via ~/.hermes/SOUL.md → the generated concat)."
else
  echo "bootstrap: SKIPPED (--write-loaders): would write ~/CLAUDE.md loader + ~/SOUL.md signpost (→ $SHELLS_DIR)"
fi

# ── Claude Code memory hooks in ~/.claude/settings.json (clone-clean) ──────────────────────────────
# settings.json lives outside any repo, so a clone has none of the memory wiring. Reproduce it here,
# idempotently: the WRITE hooks (capture: Stop/PreCompact/SessionEnd → capture.mjs) and the READ hook
# (recall: UserPromptSubmit → recall-hook.mjs, OPEN-9), plus autoMemoryEnabled:false (TOOL-6 — our
# capture.mjs is the writer, not native auto-memory). A node merge preserves every other setting and
# only appends a hook when its exact command is absent (re-run = no-op). Absolute paths (the
# settings.json convention; ~/ would not expand inside a hook command).
if [ "$WRITE_SETTINGS" -eq 1 ]; then
ENGINE_DIR="$ENGINE_DIR" SETTINGS="$HOME/.claude/settings.json" node <<'NODE'
const fs = require('fs'), path = require('path');
const engine = process.env.ENGINE_DIR, file = process.env.SETTINGS;
let s = {};
try { s = JSON.parse(fs.readFileSync(file, 'utf8')); } catch { /* fresh */ }
s.hooks ||= {};
const cmd = (script) => `node "${engine}/${script}"`;
const ensure = (event, command) => {
  s.hooks[event] ||= [];
  if (s.hooks[event].some((g) => (g.hooks || []).some((h) => h.command === command))) return false;
  s.hooks[event].push({ hooks: [{ type: 'command', command }] });
  return true;
};
let changed = false;
for (const ev of ['Stop', 'PreCompact', 'SessionEnd']) changed = ensure(ev, cmd('capture.mjs')) || changed;
changed = ensure('UserPromptSubmit', cmd('recall-hook.mjs')) || changed;      // OPEN-9 read-path
changed = ensure('UserPromptSubmit',                                          // TOOL-8 history recall (Capture layer)
  `node "${path.resolve(engine, '..', 'skills', 'history-search', 'history-search.mjs')}" hook`) || changed;
if (s.autoMemoryEnabled !== false) { s.autoMemoryEnabled = false; changed = true; }
if (changed) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(s, null, 2) + '\n');
  console.log('bootstrap: settings.json memory hooks ensured (' + file + ')');
} else {
  console.log('bootstrap: settings.json memory hooks already current');
}
NODE
else
  echo "bootstrap: SKIPPED (--write-settings): would merge memory hooks into ~/.claude/settings.json"
fi

# ── Timer installation (OS-aware) ────────────────────────────────────────────────────────────────────
if [ "$WRITE_TIMER" -ne 1 ]; then
  echo "bootstrap: SKIPPED (--write-timer): would install + enable the nightly timer running $ENGINE_DIR/dream.sh"
  exit 0
fi
OS="$(uname -s)"

if [ "$OS" = "Darwin" ]; then
  # macOS — launchd user agent (the systemd equivalent for user-space scheduled jobs).
  # NOTE: unlike systemd's Persistent=true, launchd skips a run if the machine was asleep at fire time.
  # Run `bash memory-engine/dream.sh` manually to catch up a missed night.
  PLIST_LABEL="com.cockpit.reconcile"
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/$PLIST_LABEL.plist"

  mkdir -p "$PLIST_DIR"
  # Heredoc is unquoted so $HOME/$PLIST_LABEL expand; the plist requires absolute paths.
  cat > "$PLIST_FILE" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$COCKPIT_ROOT/memory-engine/dream.sh</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>4</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>TimeoutSeconds</key>
    <integer>1800</integer>
    <key>Nice</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$MEMORY_ROOT/.reconciler/dreaming.log</string>
    <key>StandardErrorPath</key>
    <string>$MEMORY_ROOT/.reconciler/dreaming.log</string>
</dict>
</plist>
PLIST
  echo "bootstrap: wrote $PLIST_FILE"

  if [ "$INSTALL_ONLY" -eq 1 ]; then
    cat <<EOF
bootstrap: --install-only — plist written, NOT loaded. To finish:
    launchctl bootstrap gui/\$(id -u) $PLIST_FILE
    launchctl print gui/\$(id -u)/$PLIST_LABEL
EOF
    exit 0
  fi

  # Unload any previous registration (idempotent re-run), then register the updated plist.
  launchctl bootout "gui/$(id -u)/$PLIST_LABEL" 2>/dev/null || true
  launchctl bootstrap "gui/$(id -u)" "$PLIST_FILE"
  echo "bootstrap: loaded $PLIST_LABEL. Fires at 04:00 local."
  launchctl print "gui/$(id -u)/$PLIST_LABEL" 2>/dev/null | grep -E "next event|state" || true

elif command -v systemctl >/dev/null 2>&1; then
  # Linux — systemd user timer.
  UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  SERVICE="cockpit-reconcile.service"
  TIMER="cockpit-reconcile.timer"

  mkdir -p "$UNIT_DIR"

  # Heredoc unquoted so $ENGINE_DIR expands: units carry the resolved repo path (clone-clean —
  # the path comes from this script's own location, never a hardcoded root).
  cat > "$UNIT_DIR/$SERVICE" <<UNIT
[Unit]
Description=Cockpit memory reconciler — nightly "dreaming" reflect pass + insights scan (DESIGN §5/§8, §6a.8)
Documentation=file:$ENGINE_DIR/DESIGN.md

[Service]
Type=oneshot
# dream.sh sets PATH (hermes is in ~/.local/bin), runs reconcile.mjs --reflect then mechanical-insights.mjs scan
# (each tees to its own memory/.reconciler/*.log), and exits non-zero if either step failed.
ExecStart=$ENGINE_DIR/dream.sh
# A reflect pass makes a few Codex calls; cap so a hung run can't wedge the timer forever.
TimeoutStartSec=1800
Nice=10
UNIT

  cat > "$UNIT_DIR/$TIMER" <<UNIT
[Unit]
Description=Nightly trigger for the Cockpit memory "dreaming" reflect pass + insights scan
Documentation=file:$ENGINE_DIR/DESIGN.md

[Timer]
OnCalendar=*-*-* 04:00:00
# Spread the fire time so it never lands on a fixed second; harmless on a single host, tidy in logs.
RandomizedDelaySec=30min
# Laptop is often asleep at 04:00 — run once on the next wake/boot if the scheduled time was missed.
Persistent=true
AccuracySec=1min

[Install]
WantedBy=timers.target
UNIT

  systemctl --user daemon-reload
  echo "bootstrap: installed $SERVICE + $TIMER to $UNIT_DIR (daemon reloaded)."

  if [ "$INSTALL_ONLY" -eq 1 ]; then
    cat <<EOF
bootstrap: --install-only — units written, NOT enabled. To finish:
    loginctl enable-linger "$USER"
    systemctl --user enable --now $TIMER
    systemctl --user list-timers $TIMER
EOF
    exit 0
  fi

  loginctl enable-linger "$USER"
  echo "bootstrap: enabled linger for $USER (timer fires while logged out)."
  systemctl --user enable --now "$TIMER"
  echo "bootstrap: enabled + started $TIMER. Next runs:"
  systemctl --user list-timers "$TIMER" --no-pager || true

else
  echo "bootstrap: no systemd (Linux) or launchd (macOS) found." >&2
  echo "  Add a cron line to run the nightly pass (dream.sh logs its own two steps to" >&2
  echo "  memory/.reconciler/{dreaming,insights-scan}.log — no external redirect needed):" >&2
  echo "  0 4 * * * bash $ENGINE_DIR/dream.sh" >&2
  exit 1
fi
