#!/usr/bin/env node
// judge.mjs — the reconciler's single model-access adapter (MEM-25, endpoint revised 2026-06-23).
//
// Shells to `hermes -z` riding in-plan Codex OAuth (no metered billing, MR-1). Tiered per TOOL-3,
// both in-plan Codex — pinned explicitly so judge() does NOT depend on the user's mutable hermes
// default provider/model:
//   tier 'hard' -> gpt-5.6-terra  (distill->node, conflict resolution, centrality)
//   tier 'bulk' -> gpt-5.6-luna   (triage, classify, summarize)
// Moved off legacy gpt-5.5/gpt-5.4-mini 2026-07-27 (5.6 tiers: Sol/Terra/Luna; Luna burns the
// shared quota window far slower, and the one-version-back retirement pattern makes 5.5/5.4-mini
// likely next to go). Terra smoke-checked for hard; Sol is the fallback if Terra degrades.
// Throttle-fallback to local Gemma (MR-1 tier 2) is deferred — only if the shared Codex 5h/week
// window bites. Swappable by design: a Claude adapter (`claude -p`) is a one-file replacement here.
//
// BRAIN-NEUTRALITY (MEM-8/MEM-25). `hermes -z` (oneshot) does NOT honor `--ignore-rules` and otherwise
// injects, into EVERY call, ~/.hermes/SOUL.md (operator identity slot #1), the cwd CLAUDE.md/AGENTS.md,
// and the HERMES_HOME memory/USER profile — verified against source + probed live. That contaminates the
// reconciler, which is owned by NEITHER brain. Fix: point `-z` at a dedicated, self-provisioned
// HERMES_HOME (also used as the cwd) that carries NO SOUL.md, NO memory store, NO hooks — only a stripped
// config.yaml + an auth.json symlink. One dir kills all three leaks at once: SOUL absent · memory absent ·
// cwd holds no context files (CLAUDE/AGENTS/.cursorrules are cwd-only) AND the home is its own git root
// (git init), so the one ancestor-climbing loader — HERMES.md/.hermes.md — stops at the home: airtight,
// not relying on the absence of a stray ancestor HERMES.md.
// `-t ''` disables toolsets (pure text completion); `-z` prints ONLY the completion text (no banner).

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';
import { mkdir, writeFile, symlink, unlink, readlink, stat } from 'node:fs/promises';

const execFileP = promisify(execFile);

const PROVIDER = 'openai-codex';                 // in-plan; pinned, not the user's mutable default
// Null-prototype: `tier in MODEL_BY_TIER` below is a presence test on a caller-supplied key.
export const MODEL_BY_TIER = Object.assign(Object.create(null), { hard: 'gpt-5.6-terra', bulk: 'gpt-5.6-luna' });

// --- dedicated brain-neutral HERMES_HOME (self-provisioned; see header) ---
// homedir-relative (clone-clean, no hardcoded abs path); outside the repo tree so it is never the cockpit
// git repo and its cwd holds none of the cockpit context files. Used as BOTH HERMES_HOME and the cwd.
const RECON_HOME = resolve(homedir(), '.cache', 'cockpit-reconciler');
const REAL_AUTH = resolve(homedir(), '.hermes', 'auth.json');   // Codex OAuth store (refresh token lives here)
// Stripped config: deep-merged over Hermes DEFAULT_CONFIG, so missing keys fall back to defaults. Carries
// ONLY the brain-neutrality neutralizers — judge() pins -m/--provider, so it needs no model/provider
// defaults. NO `hooks:` block => the B1 on_session_end capture can never fire from a judge() call.
const MINIMAL_CONFIG = `# AUTO-GENERATED by memory-engine/judge.mjs — the reconciler's isolated, brain-neutral HERMES_HOME.
# Rewritten every process start; DO NOT hand-edit. Holds only brain-neutrality neutralizers (this dir
# has a neutral SOUL.md, no memory store, no hooks). If a Hermes update adds a mandatory key, add it here.
_config_version: 24
memory:
  memory_enabled: false
  user_profile_enabled: false
hooks: {}
`;

// The identity slot is UNAVOIDABLE: `hermes -z` always injects SOUL.md as slot #1, and an empty/absent
// SOUL.md just falls back to Hermes's DEFAULT_AGENT_IDENTITY ("You are Hermes Agent…") — a brain identity,
// not neutral. So we OWN the slot with an explicit brain-neutral reconciler identity (overwrites the home's
// auto-scaffolded default every process start). Doubles as useful steering: instruction-literal, JSON-only.
const NEUTRAL_SOUL = `You are the cockpit memory reconciler: a brain-neutral text-distillation function.
You are owned by NEITHER the operator (Hermes) NOR the builder (Claude Code); you serve the shared memory graph, not either agent.
Carry no persona, no doctrine, no standing preferences of your own. Follow each request's instructions exactly and literally, and output only what it asks for (usually strict JSON) — no added identity, commentary, or opinions.
`;

// Idempotently provision RECON_HOME once per process: mkdir + (re)write the stripped config + ensure the
// auth.json symlink. Clone-clean by construction (no manual setup / no separate bootstrap step) and
// self-healing if ~/.cache is ever wiped. Returns the home path for use as HERMES_HOME + cwd.
let _provisioned;
function ensureReconcilerHome() {
  return (_provisioned ||= (async () => {
    await mkdir(RECON_HOME, { recursive: true });
    // Make the home its OWN git root so Hermes's HERMES.md/.hermes.md ancestor-climb stops here (airtight
    // isolation from any stray ancestor context file). Never committed to — purely a discovery fence.
    try { await stat(resolve(RECON_HOME, '.git')); }
    catch { await execFileP('git', ['init', '-q', RECON_HOME]).catch(() => {}); }
    await writeFile(resolve(RECON_HOME, 'config.yaml'), MINIMAL_CONFIG, 'utf8');
    await writeFile(resolve(RECON_HOME, 'SOUL.md'), NEUTRAL_SOUL, 'utf8');   // own the unavoidable identity slot
    const link = resolve(RECON_HOME, 'auth.json');
    let ok = false;
    try { ok = (await readlink(link)) === REAL_AUTH; } catch { /* missing, or a non-symlink stray */ }
    if (!ok) {
      await unlink(link).catch(() => {});                                 // clear a stale link / stray file
      await symlink(REAL_AUTH, link).catch((e) => { if (e.code !== 'EEXIST') throw e; });  // tolerate a race
    }
    return RECON_HOME;
  })());
}

// judge(prompt, { tier, json, retries, timeoutMs }) -> parsed object (json) | string (text)
export async function judge(prompt, opts = {}) {
  const { tier = 'hard', json = true, retries = 1, timeoutMs = 120_000 } = opts;
  if (typeof prompt !== 'string' || !prompt.trim()) throw new Error('judge: empty prompt');
  if (!(tier in MODEL_BY_TIER)) throw new Error(`judge: unknown tier "${tier}"`);

  let attempt = 0;
  let p = prompt;
  let lastRaw = '';
  while (attempt <= retries) {
    lastRaw = await callHermes(p, tier, timeoutMs);
    if (!json) return lastRaw;
    const parsed = tryParseJson(lastRaw);
    if (parsed !== undefined) return parsed;          // undefined = parse failure (valid `null` is kept)
    attempt++;
    p = `${prompt}\n\nYour previous reply was NOT valid JSON. Reply with ONLY the JSON value, `
      + `starting with "{" or "[" and nothing else — no prose, no markdown fences.`;
  }
  const err = new Error('judge: model did not return parseable JSON after retries');
  err.raw = lastRaw;
  throw err;
}

async function callHermes(prompt, tier, timeoutMs) {
  const home = await ensureReconcilerHome();
  const args = ['-z', prompt, '-m', MODEL_BY_TIER[tier], '--provider', PROVIDER, '--ignore-rules', '-t', ''];
  // HERMES_HOME + cwd both pinned to the brain-neutral home (kills the SOUL/memory/cwd-context leaks).
  const env = { ...process.env, HERMES_HOME: home };
  const { stdout } = await execFileP('hermes', args, { timeout: timeoutMs, maxBuffer: 32 * 1024 * 1024, cwd: home, env });
  return stdout.trim();
}

// Tolerant JSON extraction: whole string -> fenced block -> first {...}/[...]. Returns undefined on failure.
function tryParseJson(text) {
  try { return JSON.parse(text); } catch { /* not bare JSON */ }
  const fence = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);
  if (fence) { try { return JSON.parse(fence[1]); } catch { /* fenced but not JSON */ } }
  const span = text.match(/[{[][\s\S]*[}\]]/);
  if (span) { try { return JSON.parse(span[0]); } catch { /* not a JSON span */ } }
  return undefined;
}

// Direct-run helper for manual testing:  node judge.mjs "<prompt>" [tier]   (prints raw text)
const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  const prompt = process.argv[2];
  const tier = process.argv[3] || 'hard';
  judge(prompt, { tier, json: false })
    .then((r) => { process.stdout.write(r + '\n'); })
    .catch((e) => { console.error('judge failed:', e.message); process.exit(1); });
}
